# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MAD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAD
pod ‘lottie-ios’
pod 'SnapKit', '~> 4.0.0'
pod ‘ViewAnimator’
pod 'BulletinBoard'
pod ‘CollectionKit’
pod 'ChameleonFramework/Swift'
pod ‘ScalingCarousel’
pod 'IGListKit', '~> 3.0'
pod ‘Koloda’, ‘~> 4.3.1’
pod ‘Popover’
end
